/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React, {useEffect, useState} from 'react';
import {Scene} from '../types';
import {
  ArrowPathIcon,
  ImageIcon,
  PlusIcon,
  SparklesIcon,
} from './icons';

interface StoryGeneratorProps {
  script: Scene[];
  onGenerateImage: (sceneIndex: number, prompt: string) => void;
  onCreateNew: () => void;
}

const SceneItem: React.FC<{
  scene: Scene;
  sceneIndex: number;
  onGenerate: (sceneIndex: number, prompt: string) => void;
  onPromptChange: (sceneIndex: number, newPrompt: string) => void;
}> = ({scene, sceneIndex, onGenerate, onPromptChange}) => {
  return (
    <div className="flex-shrink-0 w-80 md:w-96 bg-gray-800/50 rounded-lg border border-gray-700 flex flex-col">
      <div className="aspect-square w-full bg-gray-900/50 rounded-t-lg flex items-center justify-center overflow-hidden">
        {scene.isLoading ? (
          <div className="flex flex-col items-center text-gray-400">
            <div className="w-12 h-12 border-4 border-t-transparent border-indigo-500 rounded-full animate-spin mb-4"></div>
            <p>Generating...</p>
          </div>
        ) : scene.imageUrl ? (
          <img
            src={scene.imageUrl}
            alt={`Scene ${scene.scene}`}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="text-center text-gray-500 p-4">
            <ImageIcon className="w-16 h-16 mx-auto mb-2" />
            <p>Image will appear here</p>
          </div>
        )}
      </div>
      <div className="p-4 flex flex-col flex-grow gap-3">
        <p className="text-gray-300 text-sm">
          <strong className="text-indigo-400">Scene {scene.scene}:</strong>{' '}
          {scene.description}
        </p>
        <div className="flex-grow flex flex-col gap-2">
           <label className="text-xs font-semibold text-gray-400">Image Prompt:</label>
           <textarea
             value={scene.imagePrompt}
             onChange={(e) => onPromptChange(sceneIndex, e.target.value)}
             rows={3}
             className="w-full bg-gray-900/70 border border-gray-600 rounded-md text-sm p-2 resize-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
             placeholder="Edit image prompt..."
           />
        </div>
        <button
          onClick={() => onGenerate(sceneIndex, scene.imagePrompt)}
          disabled={scene.isLoading || !scene.imagePrompt.trim()}
          className="mt-2 w-full flex items-center justify-center gap-2 px-4 py-2 bg-indigo-600 rounded-lg hover:bg-indigo-500 text-white font-semibold text-sm transition-colors disabled:bg-gray-600 disabled:cursor-not-allowed">
          {scene.imageUrl ? (
            <ArrowPathIcon className="w-4 h-4" />
          ) : (
            <SparklesIcon className="w-4 h-4" />
          )}
          {scene.imageUrl ? 'Regenerate Image' : 'Generate Image'}
        </button>
      </div>
    </div>
  );
};

const StoryGenerator: React.FC<StoryGeneratorProps> = ({
  script,
  onGenerateImage,
  onCreateNew,
}) => {
  const [editableScript, setEditableScript] = useState<Scene[]>(script);
  const [storyTitle, setStoryTitle] = useState('');

  useEffect(() => {
    // This syncs the parent's generated script to the local editable state,
    // but only on the initial script generation. It also updates image URLs
    // when they are generated by the parent.
    setEditableScript((currentScript) =>
      script.map((newScene, index) => ({
        ...newScene,
        // Preserve local edits to the prompt
        imagePrompt: currentScript[index]?.imagePrompt || newScene.imagePrompt,
      })),
    );
  }, [script]);

  const handlePromptChange = (index: number, newPrompt: string) => {
    setEditableScript((prev) =>
      prev.map((s, i) => (i === index ? {...s, imagePrompt: newPrompt} : s)),
    );
  };

  const handleSaveStory = async () => {
    if (!storyTitle.trim() || !isComplete) return;

    // Format date and title for folder name
    const now = new Date();
    const pad = (num: number) => num.toString().padStart(2, '0');
    const dateStr = `${pad(now.getMonth() + 1)}${pad(now.getDate())}${now.getFullYear().toString().slice(-2)}-${pad(now.getHours())}${pad(now.getMinutes())}`;
    const safeTitle = storyTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const folderName = `${dateStr}-${safeTitle}`;

    // Download script.json
    const scriptContent = JSON.stringify(editableScript, null, 2);
    const scriptBlob = new Blob([scriptContent], {type: 'application/json'});
    const scriptUrl = URL.createObjectURL(scriptBlob);
    const scriptLink = document.createElement('a');
    scriptLink.href = scriptUrl;
    scriptLink.download = `${folderName}/script.json`;
    document.body.appendChild(scriptLink);
    scriptLink.click();
    document.body.removeChild(scriptLink);
    URL.revokeObjectURL(scriptUrl);

    // Download images
    for (const scene of editableScript) {
      if (scene.imageUrl) {
        // Use a temporary link to trigger the download
        const imageLink = document.createElement('a');
        imageLink.href = scene.imageUrl;
        imageLink.download = `${folderName}/scene_${scene.scene}.png`;
        document.body.appendChild(imageLink);
        imageLink.click();
        document.body.removeChild(imageLink);
        // Add a small delay between downloads to prevent browser issues
        await new Promise((resolve) => setTimeout(resolve, 200));
      }
    }
  };

  const isComplete = editableScript.every((s) => s.imageUrl);
  const canSave = isComplete && storyTitle.trim().length > 0;

  return (
    <div className="w-full flex flex-col items-center gap-8 p-4 md:p-8">
      <div className="text-center w-full max-w-2xl">
        <h2 className="text-3xl font-bold text-gray-200">
          {isComplete ? 'Your Story is Complete!' : 'Generate Your Story'}
        </h2>
        <p className="text-gray-400 mt-2">
          {isComplete
            ? 'Scroll through the film strip to see your visual narrative.'
            : 'Edit the prompts and generate an image for each scene to bring your script to life.'}
        </p>
         <input
          type="text"
          value={storyTitle}
          onChange={(e) => setStoryTitle(e.target.value)}
          placeholder="Enter your story title..."
          className="mt-6 w-full max-w-md mx-auto bg-gray-800/50 border border-gray-600 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>

      <div className="w-full flex overflow-x-auto space-x-6 pb-4">
        {editableScript.map((scene, index) => (
          <SceneItem
            key={scene.scene}
            scene={scene}
            sceneIndex={index}
            onGenerate={onGenerateImage}
            onPromptChange={handlePromptChange}
          />
        ))}
      </div>

      <div className="mt-4 flex flex-wrap justify-center gap-4">
        <button
          onClick={onCreateNew}
          className="flex items-center gap-2 px-6 py-3 bg-gray-700 hover:bg-gray-600 text-white font-semibold rounded-lg transition-colors">
          <PlusIcon className="w-5 h-5" />
          Create New Story
        </button>
        <button
          onClick={handleSaveStory}
          disabled={!canSave}
          className="flex items-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold rounded-lg transition-colors disabled:bg-gray-600 disabled:cursor-not-allowed">
          Save Story
        </button>
      </div>
    </div>
  );
};

export default StoryGenerator;
